name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:latest
    steps:

    - name: Install C Dependencies
      run: apt-get update && apt-get install gcc mesa-common-dev libsdl2 libsdl2-gfx

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build Windows x86
      run: GOOS=windows GOARCH=386 go build -v .

    - name: Upload Build Artifact Windows x86
      uses: actions/upload-artifact@v2
      with:
        name: tabula_win_x86
        path: ./tabula-editor

    - name: Build Windows amd64
      run: GOOS=windows GOARCH=amd64 go build -v .

    - name: Upload Build Artifact Windows amd64
      uses: actions/upload-artifact@v2
      with:
        name: tabula_win_amd64
        path: ./tabula-editor

    - name: Build Linux x86
      run: GOOS=linux GOARCH=386 go build -v .

    - name: Upload Build Artifact Linux x86
      uses: actions/upload-artifact@v2
      with:
        name: tabula_linux_x86
        path: ./tabula-editor

    - name: Build Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -v .

    - name: Upload Build Artifact Linux amd64
      uses: actions/upload-artifact@v2
      with:
        name: tabula_linux_amd64
        path: ./tabula-editor
