name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.28

  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:latest
    steps:

    - name: Install C Dependencies
      run: apt-get update && apt-get install -y libsdl2-dev

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Go Dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tabula-editor_linux
        path: ./tabula-editor
