name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:latest
    steps:

    - name: Install C Dependencies
      run: apt update && apt install libsdl2-gfx-dev

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tabula-editor
        path: ./tabula-editor
